# Generated by Django 5.1.7 on 2025-04-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_item_release_date"),
        ("users", "0002_remove_user_token_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="item",
        ),
        migrations.AddField(
            model_name="payment",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.cart",
                verbose_name="Оплаченный товар",
            ),
        ),
    ]
