# Generated by Django 5.1.7 on 2025-04-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_payment_item_payment_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
