# Generated by Django 5.1.7 on 2025-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordered", models.BooleanField(default=False)),
                ("total", models.IntegerField(verbose_name="Сумма заказа")),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("Завод", "Завод"),
                            ("Розничная сеть", "Розничная сеть"),
                            ("Индивидуальный предприниматель", "Индивидуальный предприниматель"),
                        ],
                        help_text="Название места производства",
                        max_length=200,
                        verbose_name="Производство",
                    ),
                ),
                ("name", models.CharField(help_text="Название фирмы", max_length=200, verbose_name="Фирма")),
                ("email", models.CharField(help_text="Адрес электронной почты", max_length=200, verbose_name="Email")),
                ("country", models.CharField(max_length=200, verbose_name="Страна")),
                ("city", models.CharField(max_length=200, verbose_name="Город")),
                ("street", models.CharField(max_length=200, verbose_name="Улица")),
                ("house", models.CharField(max_length=200, verbose_name="Номер дома")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("debt", models.IntegerField(verbose_name="Задолженность")),
            ],
            options={
                "verbose_name": "Фирма",
                "verbose_name_plural": "Фирмы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Название производимой продукции", max_length=200, verbose_name="Изделие"
                    ),
                ),
                ("mark", models.CharField(help_text="Название модели изделия", max_length=200, verbose_name="Модель")),
                ("release_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Изделие",
                "verbose_name_plural": "Изделия",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
            ],
        ),
    ]
