# Generated by Django 5.1.7 on 2025-04-10 20:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Заказанный товары", "verbose_name_plural": "Заказанные товары"},
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Время создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="order_items",
            field=models.ManyToManyField(
                related_name="order_items", to="company.orderitem", verbose_name="Заказанные издения"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заказчик",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="item",
            field=models.ManyToManyField(blank=True, related_name="items", to="company.item", verbose_name="Изделия"),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Название поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_supplier",
                to="company.company",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Время создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="company",
            field=models.CharField(
                choices=[
                    ("Завод", "Завод"),
                    ("Розничная сеть", "Розничная сеть"),
                    ("Индивидуальный предприниматель", "Индивидуальный предприниматель"),
                ],
                help_text="Название поставщика",
                max_length=200,
                verbose_name="Поставщик",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="debt",
            field=models.IntegerField(default=0, verbose_name="Задолженность"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(help_text="Адрес электронной почты", max_length=200, verbose_name="Email"),
        ),
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_per_item", models.PositiveIntegerField(verbose_name="Цена за единцу товара")),
                (
                    "quantity_available",
                    models.PositiveIntegerField(default=0, verbose_name="Количество изделий на складе"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={
                            "owner": models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Пользователь",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.item",
                        verbose_name="Изделие",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.itemprice",
                verbose_name="Изделие",
            ),
        ),
    ]
