# Generated by Django 5.1.7 on 2025-04-03 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Заказчик"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="company",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Название поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_supplier",
                to="company.company",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="item",
            field=models.ManyToManyField(related_name="items", to="company.item", verbose_name="Изделия"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order_item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="company.item", verbose_name="Изделие"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="order_items",
            field=models.ManyToManyField(
                related_name="order_items", to="company.orderitem", verbose_name="Заказанные издения"
            ),
        ),
    ]
