# Generated by Django 5.1.7 on 2025-04-10 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_cart_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemprice",
            name="item",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "owner": models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    )
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.item",
                verbose_name="Изделие",
            ),
        ),
    ]
