# Generated by Django 5.1.7 on 2025-04-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_itemprice_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemprice",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.item",
                verbose_name="Изделие",
            ),
        ),
    ]
