# Generated by Django 5.1.7 on 2025-04-12 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_itemprice_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="release_date",
            field=models.DateField(default=datetime.date),
        ),
    ]
