# Generated by Django 5.1.7 on 2025-04-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_item_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.item",
                verbose_name="Изделие",
            ),
        ),
    ]
