# Generated by Django 5.1.7 on 2025-04-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_cart_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="debt",
            new_name="balance",
        ),
    ]
