# Generated by Django 5.1.7 on 2025-04-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_rename_debt_company_balance"),
        ("users", "0004_delete_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemprice",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itemprice",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order_item",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="owner",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="company",
            new_name="company_type",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="ItemPrice",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
